<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AboutUS.aspx.cs" Inherits="Pages_AboutUS" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h2 style="margin: 0px; font-family: Helvetica, Arial, FreeSans, sans-serif; font-weight: bold; line-height: 30px; color: rgb(48, 48, 48); text-rendering: optimizelegibility; font-size: 1.8em; letter-spacing: normal; padding: 0px 0px 10px; font-style: normal; font-variant: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">Our Mission</h2>
<p style="margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Helvetica, Arial, FreeSans, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16.7999992370605px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">
    Our mission is to bring the best ingredients from around the world, right to your doorstep. With a wide variety of authentic regional grocery and spice products, we strive to reconnect people with the familiar flavors of India.</p>
<h2 style="margin: 0px; font-family: Helvetica, Arial, FreeSans, sans-serif; font-weight: bold; line-height: 30px; color: rgb(48, 48, 48); text-rendering: optimizelegibility; font-size: 1.8em; letter-spacing: normal; padding: 0px 0px 10px; font-style: normal; font-variant: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">Overview</h2>
<p style="margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Helvetica, Arial, FreeSans, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16.7999992370605px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">
    We&#39;re committed to sharing what we know best about our Indian heritage and culture: our food. We hope to continue to educate and expose new generations to the regional diversity of India and the richness of our culture and our food. India Bazaar is devoted to continuing its family tradition of personal service and exceptional quality. We guarantee that only the best spices and freshest foods will end up on your table. From our store to your plate, we hope to share the rich traditions of our ancestors with your family.</p>
<p style="margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Helvetica, Arial, FreeSans, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16.7999992370605px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">
    IndiaBazaar is U.S. based grocery retail chain that focuses on flavors and foods found in in the Indian sub-continent and the Middle East. We offer a full line of groceries including dry goods, frozen items and fresh produce.</p>
<h2 style="margin: 0px; font-family: Helvetica, Arial, FreeSans, sans-serif; font-weight: bold; line-height: 30px; color: rgb(48, 48, 48); text-rendering: optimizelegibility; font-size: 1.8em; letter-spacing: normal; padding: 0px 0px 10px; font-style: normal; font-variant: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">Our Story</h2>
<p style="margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Helvetica, Arial, FreeSans, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16.7999992370605px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">
    It was the desire to achieve more than living and working for the wealth of another that began the Patel Family&#39;s journey to build their own business. After years of working in factory assembly lines throughout the city of Greenwood, opportunity came knocking when a small Indian grocery store was for sale on little known Sheek Road. A pair of brothers and their families decided to take on this new venture and by pooling meager savings they were able to purchase the small grocery&nbsp; online.</p>
<p style="margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Helvetica, Arial, FreeSans, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16.7999992370605px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">
    After several years of hard work and success the Brothers noticed a growing influx of Indians arriving in America and living coast to coast. Even with the growing Indian population, many ingredients were not available or very expensive. As Entrepreneurs at heart, they decided to take the plunge and gave everything they had to building a national brand. Taking it 1 store at a time, we are humbled to say that Patel Brothers has 52 nationwide locations and continues to grow with several new locations planned this year.</p>
<h2 style="margin: 0px; font-family: Helvetica, Arial, FreeSans, sans-serif; font-weight: bold; line-height: 30px; color: rgb(48, 48, 48); text-rendering: optimizelegibility; font-size: 1.8em; letter-spacing: normal; padding: 0px 0px 10px; font-style: normal; font-variant: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">Our Traditions</h2>
<p style="margin: 0px 0px 10px; color: rgb(51, 51, 51); font-family: Helvetica, Arial, FreeSans, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 16.7999992370605px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(247, 247, 247);">
    Our rich heritage is closely linked to our culinary traditions. Many Indian traditions and beliefs are directly related to the foods we eat and the dishes we prepare. With the strict vegetarian diets found in many areas of India, ingredients like dals, lentils, and rice are nutritional cornerstones of Indian cuisine. The culinary diversity of India’s various regions is tied together by a common thread; no Indian meal would be complete without the intense flavor of aromatic, all-natural Indian spices.</p>
</asp:Content>

